version: '3.8'
services:
    php8:
        container_name: php8sf6
        build: php8-sf6
        ports:
            - "81:80"
        volumes:
            - ./project:/var/www/html

    mailer:
        image: schickling/mailcatcher
        ports: [ "1025", "1080" ]

    psql:
        image: postgres:14-alpine
        environment:
            POSTGRES_DB: dbtest
            POSTGRES_PASSWORD: pass
            POSTGRES_USER: user
        volumes:
            - psql:/var/lib/postgresql/data:rw
        expose:
            - "5432"
        ports:
            - "5432:5432"

volumes:
    psql:
